---
- name: Install Apache2 on Ubuntu/CentOS
  hosts: all
  become: yes

  tasks:

    - name: install updates (CentOS)
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: webservers
  become: true
  tasks:

    - name: Install Apache package
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache package
      yum:
        name: 
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"
