---
- name: Install Apache2 on Ubuntu/CentOS
  hosts: all
  become: yes

  pre_tasks:
    - name: Update packages (CentOS)
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Update packages (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- name: Install Apache package
  hosts: webservers
  become: true
  tasks:
    - name: Install Apache package on Ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache package on CentOS
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

- name: Install MariaDB on CentOS/Ubuntu
  hosts: db_servers
  become: true
  tasks:
    - name: Install MariaDB package (CentOS)
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Install MariaDB package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- name: Start and enable MariaDB service
  hosts: db_servers
  become: true
  tasks:
    - name: Start and enable MariaDB service (CentOS)
      systemd:
        name: mariadb
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Start and enable MariaDB service (Ubuntu)
      systemd:
        name: mysql
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      package:
        name: samba
        state: latest
