---
- name: Install Apache2 on Ubuntu/CentOS
  hosts: all
  become: yes
  
  tasks:

    - name: Install Apache and php packages 
      package:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes  
