---
- name: Install Apache2 on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: update repository index
      apt:
        update_cache: yes 
    - name: Install Apache package
      apt:
        name: apache2
        state: absent
    
    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: absent
